/* just to make sure there no data in the system*/
Delete From Zipcodes;
Delete From Access;
Delete From Users;
Delete From Goods;

/* Zipcodes */
insert into Zipcodes (Code, City) values ('1000', 'København K');
insert into Zipcodes (Code, City) values ('1001', 'København K');
insert into Zipcodes (Code, City) values ('1002', 'København K');
insert into Zipcodes (Code, City) values ('1003', 'København K');
insert into Zipcodes (Code, City) values ('1004', 'København K');
insert into Zipcodes (Code, City) values ('1005', 'København K');
insert into Zipcodes (Code, City) values ('1006', 'København K');
insert into Zipcodes (Code, City) values ('1007', 'København K');
insert into Zipcodes (Code, City) values ('1008', 'København K');
insert into Zipcodes (Code, City) values ('1009', 'København K');
insert into Zipcodes (Code, City) values ('1010', 'København K');
insert into Zipcodes (Code, City) values ('1011', 'København K');
insert into Zipcodes (Code, City) values ('1012', 'København K');
insert into Zipcodes (Code, City) values ('1013', 'København K');
insert into Zipcodes (Code, City) values ('1014', 'København K');
insert into Zipcodes (Code, City) values ('1015', 'København K');
insert into Zipcodes (Code, City) values ('1016', 'København K');
insert into Zipcodes (Code, City) values ('1017', 'København K');
insert into Zipcodes (Code, City) values ('1018', 'København K');
insert into Zipcodes (Code, City) values ('1019', 'København K');
insert into Zipcodes (Code, City) values ('1020', 'København K');
insert into Zipcodes (Code, City) values ('1021', 'København K');
insert into Zipcodes (Code, City) values ('1022', 'København K');
insert into Zipcodes (Code, City) values ('1023', 'København K');
insert into Zipcodes (Code, City) values ('1024', 'København K');
insert into Zipcodes (Code, City) values ('1045', 'København K');
insert into Zipcodes (Code, City) values ('1050', 'København K');
insert into Zipcodes (Code, City) values ('1051', 'København K');
insert into Zipcodes (Code, City) values ('1052', 'København K');
insert into Zipcodes (Code, City) values ('1053', 'København K');
insert into Zipcodes (Code, City) values ('1054', 'København K');
insert into Zipcodes (Code, City) values ('1055', 'København K');
insert into Zipcodes (Code, City) values ('1056', 'København K');
insert into Zipcodes (Code, City) values ('1057', 'København K');
insert into Zipcodes (Code, City) values ('1058', 'København K');
insert into Zipcodes (Code, City) values ('1059', 'København K');
insert into Zipcodes (Code, City) values ('1060', 'København K');
insert into Zipcodes (Code, City) values ('1061', 'København K');
insert into Zipcodes (Code, City) values ('1062', 'København K');
insert into Zipcodes (Code, City) values ('1063', 'København K');
insert into Zipcodes (Code, City) values ('1064', 'København K');
insert into Zipcodes (Code, City) values ('1065', 'København K');
insert into Zipcodes (Code, City) values ('1066', 'København K');
insert into Zipcodes (Code, City) values ('1067', 'København K');
insert into Zipcodes (Code, City) values ('1068', 'København K');
insert into Zipcodes (Code, City) values ('1069', 'København K');
insert into Zipcodes (Code, City) values ('1070', 'København K');
insert into Zipcodes (Code, City) values ('1071', 'København K');
insert into Zipcodes (Code, City) values ('1072', 'København K');
insert into Zipcodes (Code, City) values ('1073', 'København K');
insert into Zipcodes (Code, City) values ('1074', 'København K');
insert into Zipcodes (Code, City) values ('1091', 'København K');
insert into Zipcodes (Code, City) values ('1092', 'København K');
insert into Zipcodes (Code, City) values ('1093', 'København K');
insert into Zipcodes (Code, City) values ('1094', 'København K');
insert into Zipcodes (Code, City) values ('1095', 'København K');
insert into Zipcodes (Code, City) values ('1097', 'København K');
insert into Zipcodes (Code, City) values ('1098', 'København K');
insert into Zipcodes (Code, City) values ('1099', 'København K');
insert into Zipcodes (Code, City) values ('1100', 'København K');
insert into Zipcodes (Code, City) values ('1101', 'København K');
insert into Zipcodes (Code, City) values ('1102', 'København K');
insert into Zipcodes (Code, City) values ('1103', 'København K');
insert into Zipcodes (Code, City) values ('1104', 'København K');
insert into Zipcodes (Code, City) values ('1105', 'København K');
insert into Zipcodes (Code, City) values ('1106', 'København K');
insert into Zipcodes (Code, City) values ('1107', 'København K');
insert into Zipcodes (Code, City) values ('1110', 'København K');
insert into Zipcodes (Code, City) values ('1111', 'København K');
insert into Zipcodes (Code, City) values ('1112', 'København K');
insert into Zipcodes (Code, City) values ('1113', 'København K');
insert into Zipcodes (Code, City) values ('1114', 'København K');
insert into Zipcodes (Code, City) values ('1115', 'København K');
insert into Zipcodes (Code, City) values ('1116', 'København K');
insert into Zipcodes (Code, City) values ('1117', 'København K');
insert into Zipcodes (Code, City) values ('1118', 'København K');
insert into Zipcodes (Code, City) values ('1119', 'København K');
insert into Zipcodes (Code, City) values ('1120', 'København K');
insert into Zipcodes (Code, City) values ('1121', 'København K');
insert into Zipcodes (Code, City) values ('1122', 'København K');
insert into Zipcodes (Code, City) values ('1123', 'København K');
insert into Zipcodes (Code, City) values ('1124', 'København K');
insert into Zipcodes (Code, City) values ('1125', 'København K');
insert into Zipcodes (Code, City) values ('1126', 'København K');
insert into Zipcodes (Code, City) values ('1127', 'København K');
insert into Zipcodes (Code, City) values ('1128', 'København K');
insert into Zipcodes (Code, City) values ('1129', 'København K');
insert into Zipcodes (Code, City) values ('1130', 'København K');
insert into Zipcodes (Code, City) values ('1131', 'København K');
insert into Zipcodes (Code, City) values ('1140', 'København K');
insert into Zipcodes (Code, City) values ('1146', 'København K');
insert into Zipcodes (Code, City) values ('1147', 'København K');
insert into Zipcodes (Code, City) values ('1148', 'København K');
insert into Zipcodes (Code, City) values ('1149', 'København K');
insert into Zipcodes (Code, City) values ('1150', 'København K');
insert into Zipcodes (Code, City) values ('1151', 'København K');
insert into Zipcodes (Code, City) values ('1152', 'København K');
insert into Zipcodes (Code, City) values ('1153', 'København K');
insert into Zipcodes (Code, City) values ('1154', 'København K');
insert into Zipcodes (Code, City) values ('1155', 'København K');
insert into Zipcodes (Code, City) values ('1156', 'København K');
insert into Zipcodes (Code, City) values ('1157', 'København K');
insert into Zipcodes (Code, City) values ('1158', 'København K');
insert into Zipcodes (Code, City) values ('1159', 'København K');
insert into Zipcodes (Code, City) values ('1160', 'København K');
insert into Zipcodes (Code, City) values ('1161', 'København K');
insert into Zipcodes (Code, City) values ('1162', 'København K');
insert into Zipcodes (Code, City) values ('1163', 'København K');
insert into Zipcodes (Code, City) values ('1164', 'København K');
insert into Zipcodes (Code, City) values ('1165', 'København K');
insert into Zipcodes (Code, City) values ('1166', 'København K');
insert into Zipcodes (Code, City) values ('1167', 'København K');
insert into Zipcodes (Code, City) values ('1168', 'København K');
insert into Zipcodes (Code, City) values ('1169', 'København K');
insert into Zipcodes (Code, City) values ('1170', 'København K');
insert into Zipcodes (Code, City) values ('1171', 'København K');
insert into Zipcodes (Code, City) values ('1172', 'København K');
insert into Zipcodes (Code, City) values ('1173', 'København K');
insert into Zipcodes (Code, City) values ('1174', 'København K');
insert into Zipcodes (Code, City) values ('1175', 'København K');
insert into Zipcodes (Code, City) values ('1198', 'København K');
insert into Zipcodes (Code, City) values ('1199', 'København K');
insert into Zipcodes (Code, City) values ('1200', 'København K');
insert into Zipcodes (Code, City) values ('1201', 'København K');
insert into Zipcodes (Code, City) values ('1202', 'København K');
insert into Zipcodes (Code, City) values ('1203', 'København K');
insert into Zipcodes (Code, City) values ('1204', 'København K');
insert into Zipcodes (Code, City) values ('1205', 'København K');
insert into Zipcodes (Code, City) values ('1206', 'København K');
insert into Zipcodes (Code, City) values ('1207', 'København K');
insert into Zipcodes (Code, City) values ('1208', 'København K');
insert into Zipcodes (Code, City) values ('1209', 'København K');
insert into Zipcodes (Code, City) values ('1210', 'København K');
insert into Zipcodes (Code, City) values ('1211', 'København K');
insert into Zipcodes (Code, City) values ('1212', 'København K');
insert into Zipcodes (Code, City) values ('1213', 'København K');
insert into Zipcodes (Code, City) values ('1214', 'København K');
insert into Zipcodes (Code, City) values ('1215', 'København K');
insert into Zipcodes (Code, City) values ('1216', 'København K');
insert into Zipcodes (Code, City) values ('1217', 'København K');
insert into Zipcodes (Code, City) values ('1218', 'København K');
insert into Zipcodes (Code, City) values ('1219', 'København K');
insert into Zipcodes (Code, City) values ('1220', 'København K');
insert into Zipcodes (Code, City) values ('1221', 'København K');
insert into Zipcodes (Code, City) values ('1240', 'København K');
insert into Zipcodes (Code, City) values ('1248', 'København K');
insert into Zipcodes (Code, City) values ('1249', 'København K');
insert into Zipcodes (Code, City) values ('1250', 'København K');
insert into Zipcodes (Code, City) values ('1251', 'København K');
insert into Zipcodes (Code, City) values ('1252', 'København K');
insert into Zipcodes (Code, City) values ('1253', 'København K');
insert into Zipcodes (Code, City) values ('1254', 'København K');
insert into Zipcodes (Code, City) values ('1255', 'København K');
insert into Zipcodes (Code, City) values ('1256', 'København K');
insert into Zipcodes (Code, City) values ('1257', 'København K');
insert into Zipcodes (Code, City) values ('1258', 'København K');
insert into Zipcodes (Code, City) values ('1259', 'København K');
insert into Zipcodes (Code, City) values ('1260', 'København K');
insert into Zipcodes (Code, City) values ('1261', 'København K');
insert into Zipcodes (Code, City) values ('1262', 'København K');
insert into Zipcodes (Code, City) values ('1263', 'København K');
insert into Zipcodes (Code, City) values ('1264', 'København K');
insert into Zipcodes (Code, City) values ('1265', 'København K');
insert into Zipcodes (Code, City) values ('1266', 'København K');
insert into Zipcodes (Code, City) values ('1267', 'København K');
insert into Zipcodes (Code, City) values ('1268', 'København K');
insert into Zipcodes (Code, City) values ('1270', 'København K');
insert into Zipcodes (Code, City) values ('1271', 'København K');
insert into Zipcodes (Code, City) values ('1291', 'København K');
insert into Zipcodes (Code, City) values ('1295', 'København K');
insert into Zipcodes (Code, City) values ('1296', 'København K');
insert into Zipcodes (Code, City) values ('1298', 'København K');
insert into Zipcodes (Code, City) values ('1299', 'København K');
insert into Zipcodes (Code, City) values ('1300', 'København K');
insert into Zipcodes (Code, City) values ('1301', 'København K');
insert into Zipcodes (Code, City) values ('1302', 'København K');
insert into Zipcodes (Code, City) values ('1303', 'København K');
insert into Zipcodes (Code, City) values ('1304', 'København K');
insert into Zipcodes (Code, City) values ('1305', 'København K');
insert into Zipcodes (Code, City) values ('1306', 'København K');
insert into Zipcodes (Code, City) values ('1307', 'København K');
insert into Zipcodes (Code, City) values ('1308', 'København K');
insert into Zipcodes (Code, City) values ('1309', 'København K');
insert into Zipcodes (Code, City) values ('1310', 'København K');
insert into Zipcodes (Code, City) values ('1311', 'København K');
insert into Zipcodes (Code, City) values ('1312', 'København K');
insert into Zipcodes (Code, City) values ('1313', 'København K');
insert into Zipcodes (Code, City) values ('1314', 'København K');
insert into Zipcodes (Code, City) values ('1315', 'København K');
insert into Zipcodes (Code, City) values ('1316', 'København K');
insert into Zipcodes (Code, City) values ('1317', 'København K');
insert into Zipcodes (Code, City) values ('1318', 'København K');
insert into Zipcodes (Code, City) values ('1319', 'København K');
insert into Zipcodes (Code, City) values ('1320', 'København K');
insert into Zipcodes (Code, City) values ('1321', 'København K');
insert into Zipcodes (Code, City) values ('1322', 'København K');
insert into Zipcodes (Code, City) values ('1323', 'København K');
insert into Zipcodes (Code, City) values ('1324', 'København K');
insert into Zipcodes (Code, City) values ('1325', 'København K');
insert into Zipcodes (Code, City) values ('1326', 'København K');
insert into Zipcodes (Code, City) values ('1327', 'København K');
insert into Zipcodes (Code, City) values ('1328', 'København K');
insert into Zipcodes (Code, City) values ('1329', 'København K');
insert into Zipcodes (Code, City) values ('1347', 'København K');
insert into Zipcodes (Code, City) values ('1349', 'København K');
insert into Zipcodes (Code, City) values ('1350', 'København K');
insert into Zipcodes (Code, City) values ('1352', 'København K');
insert into Zipcodes (Code, City) values ('1353', 'København K');
insert into Zipcodes (Code, City) values ('1354', 'København K');
insert into Zipcodes (Code, City) values ('1355', 'København K');
insert into Zipcodes (Code, City) values ('1356', 'København K');
insert into Zipcodes (Code, City) values ('1357', 'København K');
insert into Zipcodes (Code, City) values ('1358', 'København K');
insert into Zipcodes (Code, City) values ('1359', 'København K');
insert into Zipcodes (Code, City) values ('1360', 'København K');
insert into Zipcodes (Code, City) values ('1361', 'København K');
insert into Zipcodes (Code, City) values ('1362', 'København K');
insert into Zipcodes (Code, City) values ('1363', 'København K');
insert into Zipcodes (Code, City) values ('1364', 'København K');
insert into Zipcodes (Code, City) values ('1365', 'København K');
insert into Zipcodes (Code, City) values ('1366', 'København K');
insert into Zipcodes (Code, City) values ('1367', 'København K');
insert into Zipcodes (Code, City) values ('1368', 'København K');
insert into Zipcodes (Code, City) values ('1369', 'København K');
insert into Zipcodes (Code, City) values ('1370', 'København K');
insert into Zipcodes (Code, City) values ('1371', 'København K');
insert into Zipcodes (Code, City) values ('1399', 'København K');
insert into Zipcodes (Code, City) values ('1400', 'København K');
insert into Zipcodes (Code, City) values ('1401', 'København K');
insert into Zipcodes (Code, City) values ('1402', 'København K');
insert into Zipcodes (Code, City) values ('1403', 'København K');
insert into Zipcodes (Code, City) values ('1404', 'København K');
insert into Zipcodes (Code, City) values ('1405', 'København K');
insert into Zipcodes (Code, City) values ('1406', 'København K');
insert into Zipcodes (Code, City) values ('1407', 'København K');
insert into Zipcodes (Code, City) values ('1408', 'København K');
insert into Zipcodes (Code, City) values ('1409', 'København K');
insert into Zipcodes (Code, City) values ('1410', 'København K');
insert into Zipcodes (Code, City) values ('1411', 'København K');
insert into Zipcodes (Code, City) values ('1412', 'København K');
insert into Zipcodes (Code, City) values ('1413', 'København K');
insert into Zipcodes (Code, City) values ('1414', 'København K');
insert into Zipcodes (Code, City) values ('1415', 'København K');
insert into Zipcodes (Code, City) values ('1416', 'København K');
insert into Zipcodes (Code, City) values ('1417', 'København K');
insert into Zipcodes (Code, City) values ('1418', 'København K');
insert into Zipcodes (Code, City) values ('1419', 'København K');
insert into Zipcodes (Code, City) values ('1420', 'København K');
insert into Zipcodes (Code, City) values ('1421', 'København K');
insert into Zipcodes (Code, City) values ('1422', 'København K');
insert into Zipcodes (Code, City) values ('1423', 'København K');
insert into Zipcodes (Code, City) values ('1424', 'København K');
insert into Zipcodes (Code, City) values ('1425', 'København K');
insert into Zipcodes (Code, City) values ('1426', 'København K');
insert into Zipcodes (Code, City) values ('1427', 'København K');
insert into Zipcodes (Code, City) values ('1428', 'København K');
insert into Zipcodes (Code, City) values ('1429', 'København K');
insert into Zipcodes (Code, City) values ('1430', 'København K');
insert into Zipcodes (Code, City) values ('1431', 'København K');
insert into Zipcodes (Code, City) values ('1432', 'København K');
insert into Zipcodes (Code, City) values ('1433', 'København K');
insert into Zipcodes (Code, City) values ('1439', 'København K');
insert into Zipcodes (Code, City) values ('1448', 'København K');
insert into Zipcodes (Code, City) values ('1449', 'København K');
insert into Zipcodes (Code, City) values ('1450', 'København K');
insert into Zipcodes (Code, City) values ('1451', 'København K');
insert into Zipcodes (Code, City) values ('1452', 'København K');
insert into Zipcodes (Code, City) values ('1453', 'København K');
insert into Zipcodes (Code, City) values ('1454', 'København K');
insert into Zipcodes (Code, City) values ('1455', 'København K');
insert into Zipcodes (Code, City) values ('1456', 'København K');
insert into Zipcodes (Code, City) values ('1457', 'København K');
insert into Zipcodes (Code, City) values ('1458', 'København K');
insert into Zipcodes (Code, City) values ('1459', 'København K');
insert into Zipcodes (Code, City) values ('1460', 'København K');
insert into Zipcodes (Code, City) values ('1461', 'København K');
insert into Zipcodes (Code, City) values ('1462', 'København K');
insert into Zipcodes (Code, City) values ('1463', 'København K');
insert into Zipcodes (Code, City) values ('1464', 'København K');
insert into Zipcodes (Code, City) values ('1465', 'København K');
insert into Zipcodes (Code, City) values ('1466', 'København K');
insert into Zipcodes (Code, City) values ('1467', 'København K');
insert into Zipcodes (Code, City) values ('1468', 'København K');
insert into Zipcodes (Code, City) values ('1470', 'København K');
insert into Zipcodes (Code, City) values ('1471', 'København K');
insert into Zipcodes (Code, City) values ('1472', 'København K');
insert into Zipcodes (Code, City) values ('1473', 'København K');
insert into Zipcodes (Code, City) values ('1500', 'København V');
insert into Zipcodes (Code, City) values ('1501', 'København V');
insert into Zipcodes (Code, City) values ('1502', 'København V');
insert into Zipcodes (Code, City) values ('1503', 'København V');
insert into Zipcodes (Code, City) values ('1504', 'København V');
insert into Zipcodes (Code, City) values ('1505', 'København V');
insert into Zipcodes (Code, City) values ('1506', 'København V');
insert into Zipcodes (Code, City) values ('1507', 'København V');
insert into Zipcodes (Code, City) values ('1508', 'København V');
insert into Zipcodes (Code, City) values ('1509', 'København V');
insert into Zipcodes (Code, City) values ('1510', 'København V');
insert into Zipcodes (Code, City) values ('1525', 'København V');
insert into Zipcodes (Code, City) values ('1530', 'København V');
insert into Zipcodes (Code, City) values ('1533', 'København V');
insert into Zipcodes (Code, City) values ('1534', 'København V');
insert into Zipcodes (Code, City) values ('1535', 'København V');
insert into Zipcodes (Code, City) values ('1550', 'København V');
insert into Zipcodes (Code, City) values ('1551', 'København V');
insert into Zipcodes (Code, City) values ('1552', 'København V');
insert into Zipcodes (Code, City) values ('1553', 'København V');
insert into Zipcodes (Code, City) values ('1554', 'København V');
insert into Zipcodes (Code, City) values ('1555', 'København V');
insert into Zipcodes (Code, City) values ('1556', 'København V');
insert into Zipcodes (Code, City) values ('1557', 'København V');
insert into Zipcodes (Code, City) values ('1558', 'København V');
insert into Zipcodes (Code, City) values ('1559', 'København V');
insert into Zipcodes (Code, City) values ('1560', 'København V');
insert into Zipcodes (Code, City) values ('1561', 'København V');
insert into Zipcodes (Code, City) values ('1562', 'København V');
insert into Zipcodes (Code, City) values ('1563', 'København V');
insert into Zipcodes (Code, City) values ('1564', 'København V');
insert into Zipcodes (Code, City) values ('1567', 'København V');
insert into Zipcodes (Code, City) values ('1568', 'København V');
insert into Zipcodes (Code, City) values ('1569', 'København V');
insert into Zipcodes (Code, City) values ('1570', 'København V');
insert into Zipcodes (Code, City) values ('1571', 'København V');
insert into Zipcodes (Code, City) values ('1572', 'København V');
insert into Zipcodes (Code, City) values ('1573', 'København V');
insert into Zipcodes (Code, City) values ('1574', 'København V');
insert into Zipcodes (Code, City) values ('1575', 'København V');
insert into Zipcodes (Code, City) values ('1576', 'København V');
insert into Zipcodes (Code, City) values ('1577', 'København V');
insert into Zipcodes (Code, City) values ('1579', 'København V');
insert into Zipcodes (Code, City) values ('1580', 'København V');
insert into Zipcodes (Code, City) values ('1581', 'København V');
insert into Zipcodes (Code, City) values ('1583', 'København V');
insert into Zipcodes (Code, City) values ('1585', 'København V');
insert into Zipcodes (Code, City) values ('1588', 'København V');
insert into Zipcodes (Code, City) values ('1590', 'København V');
insert into Zipcodes (Code, City) values ('1592', 'København V');
insert into Zipcodes (Code, City) values ('1593', 'København V');
insert into Zipcodes (Code, City) values ('1595', 'København V');
insert into Zipcodes (Code, City) values ('1596', 'København V');
insert into Zipcodes (Code, City) values ('1598', 'København V');
insert into Zipcodes (Code, City) values ('1599', 'København V');
insert into Zipcodes (Code, City) values ('1600', 'København V');
insert into Zipcodes (Code, City) values ('1601', 'København V');
insert into Zipcodes (Code, City) values ('1602', 'København V');
insert into Zipcodes (Code, City) values ('1603', 'København V');
insert into Zipcodes (Code, City) values ('1604', 'København V');
insert into Zipcodes (Code, City) values ('1605', 'København V');
insert into Zipcodes (Code, City) values ('1606', 'København V');
insert into Zipcodes (Code, City) values ('1607', 'København V');
insert into Zipcodes (Code, City) values ('1608', 'København V');
insert into Zipcodes (Code, City) values ('1609', 'København V');
insert into Zipcodes (Code, City) values ('1610', 'København V');
insert into Zipcodes (Code, City) values ('1611', 'København V');
insert into Zipcodes (Code, City) values ('1612', 'København V');
insert into Zipcodes (Code, City) values ('1613', 'København V');
insert into Zipcodes (Code, City) values ('1614', 'København V');
insert into Zipcodes (Code, City) values ('1615', 'København V');
insert into Zipcodes (Code, City) values ('1616', 'København V');
insert into Zipcodes (Code, City) values ('1617', 'København V');
insert into Zipcodes (Code, City) values ('1618', 'København V');
insert into Zipcodes (Code, City) values ('1619', 'København V');
insert into Zipcodes (Code, City) values ('1620', 'København V');
insert into Zipcodes (Code, City) values ('1621', 'København V');
insert into Zipcodes (Code, City) values ('1622', 'København V');
insert into Zipcodes (Code, City) values ('1623', 'København V');
insert into Zipcodes (Code, City) values ('1624', 'København V');
insert into Zipcodes (Code, City) values ('1625', 'København V');
insert into Zipcodes (Code, City) values ('1631', 'København V');
insert into Zipcodes (Code, City) values ('1632', 'København V');
insert into Zipcodes (Code, City) values ('1633', 'København V');
insert into Zipcodes (Code, City) values ('1634', 'København V');
insert into Zipcodes (Code, City) values ('1635', 'København V');
insert into Zipcodes (Code, City) values ('1639', 'København V');
insert into Zipcodes (Code, City) values ('1640', 'København V');
insert into Zipcodes (Code, City) values ('1642', 'København V');
insert into Zipcodes (Code, City) values ('1643', 'København V');
insert into Zipcodes (Code, City) values ('1644', 'København V');
insert into Zipcodes (Code, City) values ('1645', 'København V');
insert into Zipcodes (Code, City) values ('1648', 'København V');
insert into Zipcodes (Code, City) values ('1650', 'København V');
insert into Zipcodes (Code, City) values ('1651', 'København V');
insert into Zipcodes (Code, City) values ('1652', 'København V');
insert into Zipcodes (Code, City) values ('1653', 'København K');
insert into Zipcodes (Code, City) values ('1654', 'København V');
insert into Zipcodes (Code, City) values ('1655', 'København V');
insert into Zipcodes (Code, City) values ('1656', 'København V');
insert into Zipcodes (Code, City) values ('1657', 'København V');
insert into Zipcodes (Code, City) values ('1658', 'København V');
insert into Zipcodes (Code, City) values ('1659', 'København V');
insert into Zipcodes (Code, City) values ('1660', 'København V');
insert into Zipcodes (Code, City) values ('1661', 'København V');
insert into Zipcodes (Code, City) values ('1662', 'København V');
insert into Zipcodes (Code, City) values ('1663', 'København V');
insert into Zipcodes (Code, City) values ('1664', 'København V');
insert into Zipcodes (Code, City) values ('1665', 'København V');
insert into Zipcodes (Code, City) values ('1666', 'København V');
insert into Zipcodes (Code, City) values ('1667', 'København V');
insert into Zipcodes (Code, City) values ('1668', 'København V');
insert into Zipcodes (Code, City) values ('1669', 'København V');
insert into Zipcodes (Code, City) values ('1670', 'København V');
insert into Zipcodes (Code, City) values ('1671', 'København V');
insert into Zipcodes (Code, City) values ('1672', 'København V');
insert into Zipcodes (Code, City) values ('1673', 'København V');
insert into Zipcodes (Code, City) values ('1674', 'København V');
insert into Zipcodes (Code, City) values ('1675', 'København V');
insert into Zipcodes (Code, City) values ('1676', 'København V');
insert into Zipcodes (Code, City) values ('1677', 'København V');
insert into Zipcodes (Code, City) values ('1700', 'København V');
insert into Zipcodes (Code, City) values ('1701', 'København V');
insert into Zipcodes (Code, City) values ('1702', 'København V');
insert into Zipcodes (Code, City) values ('1703', 'København V');
insert into Zipcodes (Code, City) values ('1704', 'København V');
insert into Zipcodes (Code, City) values ('1705', 'København V');
insert into Zipcodes (Code, City) values ('1706', 'København V');
insert into Zipcodes (Code, City) values ('1707', 'København V');
insert into Zipcodes (Code, City) values ('1708', 'København V');
insert into Zipcodes (Code, City) values ('1709', 'København V');
insert into Zipcodes (Code, City) values ('1710', 'København V');
insert into Zipcodes (Code, City) values ('1711', 'København V');
insert into Zipcodes (Code, City) values ('1712', 'København V');
insert into Zipcodes (Code, City) values ('1713', 'København V');
insert into Zipcodes (Code, City) values ('1714', 'København V');
insert into Zipcodes (Code, City) values ('1715', 'København V');
insert into Zipcodes (Code, City) values ('1716', 'København V');
insert into Zipcodes (Code, City) values ('1717', 'København V');
insert into Zipcodes (Code, City) values ('1718', 'København V');
insert into Zipcodes (Code, City) values ('1719', 'København V');
insert into Zipcodes (Code, City) values ('1720', 'København V');
insert into Zipcodes (Code, City) values ('1721', 'København V');
insert into Zipcodes (Code, City) values ('1722', 'København V');
insert into Zipcodes (Code, City) values ('1723', 'København V');
insert into Zipcodes (Code, City) values ('1724', 'København V');
insert into Zipcodes (Code, City) values ('1725', 'København v');
insert into Zipcodes (Code, City) values ('1726', 'København V');
insert into Zipcodes (Code, City) values ('1727', 'København V');
insert into Zipcodes (Code, City) values ('1728', 'København V');
insert into Zipcodes (Code, City) values ('1729', 'København V');
insert into Zipcodes (Code, City) values ('1730', 'København V');
insert into Zipcodes (Code, City) values ('1731', 'København V');
insert into Zipcodes (Code, City) values ('1732', 'København V');
insert into Zipcodes (Code, City) values ('1733', 'København V');
insert into Zipcodes (Code, City) values ('1734', 'København V');
insert into Zipcodes (Code, City) values ('1735', 'København V');
insert into Zipcodes (Code, City) values ('1736', 'København V');
insert into Zipcodes (Code, City) values ('1737', 'København V');
insert into Zipcodes (Code, City) values ('1738', 'København V');
insert into Zipcodes (Code, City) values ('1739', 'København V');
insert into Zipcodes (Code, City) values ('1748', 'København V');
insert into Zipcodes (Code, City) values ('1749', 'København V');
insert into Zipcodes (Code, City) values ('1750', 'København V');
insert into Zipcodes (Code, City) values ('1751', 'København V');
insert into Zipcodes (Code, City) values ('1752', 'København V');
insert into Zipcodes (Code, City) values ('1753', 'København V');
insert into Zipcodes (Code, City) values ('1754', 'København V');
insert into Zipcodes (Code, City) values ('1755', 'København V');
insert into Zipcodes (Code, City) values ('1756', 'København V');
insert into Zipcodes (Code, City) values ('1757', 'København V');
insert into Zipcodes (Code, City) values ('1758', 'København V');
insert into Zipcodes (Code, City) values ('1759', 'København V');
insert into Zipcodes (Code, City) values ('1760', 'København V');
insert into Zipcodes (Code, City) values ('1761', 'København V');
insert into Zipcodes (Code, City) values ('1762', 'København V');
insert into Zipcodes (Code, City) values ('1763', 'København V');
insert into Zipcodes (Code, City) values ('1764', 'København V');
insert into Zipcodes (Code, City) values ('1765', 'København V');
insert into Zipcodes (Code, City) values ('1766', 'København V');
insert into Zipcodes (Code, City) values ('1770', 'København V');
insert into Zipcodes (Code, City) values ('1771', 'København V');
insert into Zipcodes (Code, City) values ('1772', 'København V');
insert into Zipcodes (Code, City) values ('1773', 'København V');
insert into Zipcodes (Code, City) values ('1774', 'København V');
insert into Zipcodes (Code, City) values ('1775', 'København V');
insert into Zipcodes (Code, City) values ('1776', 'København V');
insert into Zipcodes (Code, City) values ('1777', 'København V');
insert into Zipcodes (Code, City) values ('1778', 'København V');
insert into Zipcodes (Code, City) values ('1780', 'København V');
insert into Zipcodes (Code, City) values ('1781', 'København V');
insert into Zipcodes (Code, City) values ('1785', 'København V');
insert into Zipcodes (Code, City) values ('1786', 'København V');
insert into Zipcodes (Code, City) values ('1790', 'København V');
insert into Zipcodes (Code, City) values ('1795', 'København V');
insert into Zipcodes (Code, City) values ('1799', 'København V');
insert into Zipcodes (Code, City) values ('1800', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1801', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1802', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1803', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1804', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1805', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1806', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1807', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1808', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1809', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1810', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1811', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1812', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1813', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1814', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1815', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1816', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1817', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1818', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1819', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1820', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1822', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1823', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1824', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1825', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1826', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1827', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1828', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1829', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1835', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1850', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1851', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1852', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1853', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1854', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1855', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1856', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1857', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1860', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1861', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1862', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1863', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1864', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1865', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1866', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1867', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1868', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1870', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1871', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1872', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1873', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1874', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1875', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1876', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1877', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1878', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1879', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1899', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1900', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1901', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1902', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1903', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1904', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1905', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1906', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1908', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1909', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1910', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1911', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1912', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1913', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1914', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1915', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1916', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1917', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1918', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1920', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1921', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1922', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1923', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1924', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1925', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1926', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1927', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1928', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1931', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1950', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1951', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1952', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1953', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1954', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1955', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1956', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1957', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1958', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1959', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1960', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1961', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1962', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1963', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1964', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1965', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1966', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1967', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1970', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1971', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1972', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1973', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1974', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1998', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('1999', 'Frederiksberg C');
insert into Zipcodes (Code, City) values ('2000', 'Frederiksberg');
insert into Zipcodes (Code, City) values ('2100', 'København Ø');
insert into Zipcodes (Code, City) values ('2200', 'København N');
insert into Zipcodes (Code, City) values ('2300', 'København S');
insert into Zipcodes (Code, City) values ('2400', 'København NV');
insert into Zipcodes (Code, City) values ('2450', 'København SV');
insert into Zipcodes (Code, City) values ('2500', 'Valby');
insert into Zipcodes (Code, City) values ('2600', 'Glostrup');
insert into Zipcodes (Code, City) values ('2605', 'Brøndby');
insert into Zipcodes (Code, City) values ('2610', 'Rødovre');
insert into Zipcodes (Code, City) values ('2620', 'Albertslund');
insert into Zipcodes (Code, City) values ('2625', 'Vallensbæk');
insert into Zipcodes (Code, City) values ('2630', 'Taastrup');
insert into Zipcodes (Code, City) values ('2633', 'Høje Tåstrup');
insert into Zipcodes (Code, City) values ('2635', 'Ishøj');
insert into Zipcodes (Code, City) values ('2640', 'Hedehusene');
insert into Zipcodes (Code, City) values ('2650', 'Hvidovre');
insert into Zipcodes (Code, City) values ('2660', 'Brøndby Strand');
insert into Zipcodes (Code, City) values ('2665', 'Vallensbæk strand');
insert into Zipcodes (Code, City) values ('2670', 'Greve');
insert into Zipcodes (Code, City) values ('2680', 'Solrød Strand');
insert into Zipcodes (Code, City) values ('2690', 'Karlslunde');
insert into Zipcodes (Code, City) values ('2700', 'Brønshøj');
insert into Zipcodes (Code, City) values ('2720', 'Vanløse');
insert into Zipcodes (Code, City) values ('2730', 'Herlev');
insert into Zipcodes (Code, City) values ('2740', 'Skovlunde');
insert into Zipcodes (Code, City) values ('2750', 'Ballerup');
insert into Zipcodes (Code, City) values ('2760', 'Måløv');
insert into Zipcodes (Code, City) values ('2765', 'Smørum');
insert into Zipcodes (Code, City) values ('2770', 'Kastrup');
insert into Zipcodes (Code, City) values ('2791', 'Dragør');
insert into Zipcodes (Code, City) values ('2800', 'Lyngby');
insert into Zipcodes (Code, City) values ('2820', 'Gentofte');
insert into Zipcodes (Code, City) values ('2830', 'Virum');
insert into Zipcodes (Code, City) values ('2840', 'Holte');
insert into Zipcodes (Code, City) values ('2850', 'Nærum');
insert into Zipcodes (Code, City) values ('2860', 'Søborg');
insert into Zipcodes (Code, City) values ('2880', 'Bagsværd');
insert into Zipcodes (Code, City) values ('2900', 'Hellerup');
insert into Zipcodes (Code, City) values ('2920', 'Charlottenlund');
insert into Zipcodes (Code, City) values ('2930', 'Klampenborg');
insert into Zipcodes (Code, City) values ('2942', 'Skodsborg');
insert into Zipcodes (Code, City) values ('2950', 'Vedbæk');
insert into Zipcodes (Code, City) values ('2960', 'Rungsted Kyst');
insert into Zipcodes (Code, City) values ('2970', 'Hørsholm');
insert into Zipcodes (Code, City) values ('2980', 'Kokkedal');
insert into Zipcodes (Code, City) values ('2990', 'Nivå');
insert into Zipcodes (Code, City) values ('3000', 'Helsingør');
insert into Zipcodes (Code, City) values ('3050', 'Humlebæk');
insert into Zipcodes (Code, City) values ('3060', 'Espergærde');
insert into Zipcodes (Code, City) values ('3070', 'Snekkersten');
insert into Zipcodes (Code, City) values ('3080', 'Tikøb');
insert into Zipcodes (Code, City) values ('3100', 'Hornbæk');
insert into Zipcodes (Code, City) values ('3120', 'Dronningmølle');
insert into Zipcodes (Code, City) values ('3140', 'Ålsgårde');
insert into Zipcodes (Code, City) values ('3150', 'Hellebæk');
insert into Zipcodes (Code, City) values ('3200', 'Helsinge');
insert into Zipcodes (Code, City) values ('3210', 'Vejby');
insert into Zipcodes (Code, City) values ('3220', 'Tisvildeleje');
insert into Zipcodes (Code, City) values ('3230', 'Græsted');
insert into Zipcodes (Code, City) values ('3250', 'Gilleleje');
insert into Zipcodes (Code, City) values ('3300', 'Frederiksværk');
insert into Zipcodes (Code, City) values ('3310', 'Ølsted');
insert into Zipcodes (Code, City) values ('3320', 'Skævinge');
insert into Zipcodes (Code, City) values ('3330', 'Gørløse');
insert into Zipcodes (Code, City) values ('3360', 'Liseleje');
insert into Zipcodes (Code, City) values ('3370', 'Melby');
insert into Zipcodes (Code, City) values ('3390', 'Hundested');
insert into Zipcodes (Code, City) values ('3400', 'Hillerød');
insert into Zipcodes (Code, City) values ('3450', 'Allerød');
insert into Zipcodes (Code, City) values ('3460', 'Birkerød');
insert into Zipcodes (Code, City) values ('3480', 'Fredensborg');
insert into Zipcodes (Code, City) values ('3490', 'Kvistgård');
insert into Zipcodes (Code, City) values ('3500', 'Værløse');
insert into Zipcodes (Code, City) values ('3520', 'Farum');
insert into Zipcodes (Code, City) values ('3540', 'Lynge');
insert into Zipcodes (Code, City) values ('3550', 'Slangerup');
insert into Zipcodes (Code, City) values ('3600', 'Frederikssund');
insert into Zipcodes (Code, City) values ('3630', 'Jægerspris');
insert into Zipcodes (Code, City) values ('3650', 'Ølstykke');
insert into Zipcodes (Code, City) values ('3660', 'Stenløse');
insert into Zipcodes (Code, City) values ('3670', 'Veksø Sjælland');
insert into Zipcodes (Code, City) values ('3700', 'Rønne');
insert into Zipcodes (Code, City) values ('3720', 'Aakirkeby');
insert into Zipcodes (Code, City) values ('3730', 'Neksø');
insert into Zipcodes (Code, City) values ('3740', 'Svaneke');
insert into Zipcodes (Code, City) values ('3751', 'Østermarie');
insert into Zipcodes (Code, City) values ('3760', 'Gudhjem');
insert into Zipcodes (Code, City) values ('3770', 'Allinge');
insert into Zipcodes (Code, City) values ('3782', 'Klemensker');
insert into Zipcodes (Code, City) values ('3790', 'Hasle');
insert into Zipcodes (Code, City) values ('3900', 'Nuuk');
insert into Zipcodes (Code, City) values ('3905', 'Nuussuaq');
insert into Zipcodes (Code, City) values ('3910', 'Kangerlussuaq');
insert into Zipcodes (Code, City) values ('3911', 'Sisimiut');
insert into Zipcodes (Code, City) values ('3912', 'Maniitsoq');
insert into Zipcodes (Code, City) values ('3913', 'Ammasalik');
insert into Zipcodes (Code, City) values ('3915', 'Kulusuk');
insert into Zipcodes (Code, City) values ('3920', 'Qaqortoq');
insert into Zipcodes (Code, City) values ('3921', 'Narsaq');
insert into Zipcodes (Code, City) values ('3922', 'Nanortalik');
insert into Zipcodes (Code, City) values ('3923', 'Narsarsuaq');
insert into Zipcodes (Code, City) values ('3924', 'Ikerasassuaq');
insert into Zipcodes (Code, City) values ('3927', 'Angisoq');
insert into Zipcodes (Code, City) values ('3930', 'Kangilinnguit');
insert into Zipcodes (Code, City) values ('3932', 'Arsuk');
insert into Zipcodes (Code, City) values ('3940', 'Paamiut');
insert into Zipcodes (Code, City) values ('3950', 'Aasiaat');
insert into Zipcodes (Code, City) values ('3951', 'Qasigiannguit');
insert into Zipcodes (Code, City) values ('3952', 'Ilulissat');
insert into Zipcodes (Code, City) values ('3953', 'Qeqertarsuaq');
insert into Zipcodes (Code, City) values ('3955', 'Kangaatsiaq');
insert into Zipcodes (Code, City) values ('3961', 'Uummannaq');
insert into Zipcodes (Code, City) values ('3962', 'Upernavik');
insert into Zipcodes (Code, City) values ('3970', 'Dundas');
insert into Zipcodes (Code, City) values ('3971', 'Qaanaaq');
insert into Zipcodes (Code, City) values ('3980', 'Ittoqqortoormii');
insert into Zipcodes (Code, City) values ('3984', 'Danmarkshavn');
insert into Zipcodes (Code, City) values ('3985', 'Constable Pynt');
insert into Zipcodes (Code, City) values ('3992', 'Slædepatruljen Siriu');
insert into Zipcodes (Code, City) values ('4000', 'Roskilde');
insert into Zipcodes (Code, City) values ('4040', 'Jyllinge');
insert into Zipcodes (Code, City) values ('4050', 'Skibby');
insert into Zipcodes (Code, City) values ('4060', 'Kirke-Såby');
insert into Zipcodes (Code, City) values ('4070', 'Kirke-Hyllinge');
insert into Zipcodes (Code, City) values ('4100', 'Ringsted');
insert into Zipcodes (Code, City) values ('4130', 'Viby Sjælland');
insert into Zipcodes (Code, City) values ('4140', 'Borup');
insert into Zipcodes (Code, City) values ('4160', 'Herlufmagle');
insert into Zipcodes (Code, City) values ('4171', 'Glumsø');
insert into Zipcodes (Code, City) values ('4173', 'Fjenneslev');
insert into Zipcodes (Code, City) values ('4174', 'Jystrup Midtsj.');
insert into Zipcodes (Code, City) values ('4180', 'Sorø');
insert into Zipcodes (Code, City) values ('4190', 'Munke-Bjergby');
insert into Zipcodes (Code, City) values ('4200', 'Slagelse');
insert into Zipcodes (Code, City) values ('4220', 'Korsør');
insert into Zipcodes (Code, City) values ('4230', 'Skælskør');
insert into Zipcodes (Code, City) values ('4241', 'Vemmelev');
insert into Zipcodes (Code, City) values ('4242', 'Boeslunde');
insert into Zipcodes (Code, City) values ('4243', 'Rude');
insert into Zipcodes (Code, City) values ('4250', 'Fuglebjerg');
insert into Zipcodes (Code, City) values ('4261', 'Dalmose');
insert into Zipcodes (Code, City) values ('4262', 'Sandved');
insert into Zipcodes (Code, City) values ('4270', 'Høng');
insert into Zipcodes (Code, City) values ('4281', 'Gørlev');
insert into Zipcodes (Code, City) values ('4291', 'Ruds-Vedby');
insert into Zipcodes (Code, City) values ('4293', 'Dianalund');
insert into Zipcodes (Code, City) values ('4295', 'Stenlille');
insert into Zipcodes (Code, City) values ('4296', 'Nyrup');
insert into Zipcodes (Code, City) values ('4300', 'Holbæk');
insert into Zipcodes (Code, City) values ('4320', 'Lejre');
insert into Zipcodes (Code, City) values ('4330', 'Hvalsø');
insert into Zipcodes (Code, City) values ('4340', 'Tølløse');
insert into Zipcodes (Code, City) values ('4350', 'Ugerløse');
insert into Zipcodes (Code, City) values ('4360', 'Kirke-Eskilstrup');
insert into Zipcodes (Code, City) values ('4370', 'Store-Merløse');
insert into Zipcodes (Code, City) values ('4390', 'Vipperød');
insert into Zipcodes (Code, City) values ('4400', 'Kalundborg');
insert into Zipcodes (Code, City) values ('4420', 'Regstrup');
insert into Zipcodes (Code, City) values ('4440', 'Mørkøv');
insert into Zipcodes (Code, City) values ('4450', 'Jyderup');
insert into Zipcodes (Code, City) values ('4460', 'Snertinge');
insert into Zipcodes (Code, City) values ('4470', 'Svebølle');
insert into Zipcodes (Code, City) values ('4480', 'Store-Fuglede');
insert into Zipcodes (Code, City) values ('4490', 'Jerslev Sjælland');
insert into Zipcodes (Code, City) values ('4500', 'Nykøbing Sj.');
insert into Zipcodes (Code, City) values ('4520', 'Svinninge');
insert into Zipcodes (Code, City) values ('4532', 'Gislinge');
insert into Zipcodes (Code, City) values ('4534', 'Hørve');
insert into Zipcodes (Code, City) values ('4540', 'Fårevejle');
insert into Zipcodes (Code, City) values ('4550', 'Asnæs');
insert into Zipcodes (Code, City) values ('4560', 'Vig');
insert into Zipcodes (Code, City) values ('4571', 'Grevinge');
insert into Zipcodes (Code, City) values ('4572', 'Nørre-Asmindrup');
insert into Zipcodes (Code, City) values ('4573', 'Højby');
insert into Zipcodes (Code, City) values ('4581', 'Rørvig');
insert into Zipcodes (Code, City) values ('4583', 'Sjællands Odde');
insert into Zipcodes (Code, City) values ('4591', 'Føllenslev');
insert into Zipcodes (Code, City) values ('4592', 'Sejerø');
insert into Zipcodes (Code, City) values ('4593', 'Eskebjerg');
insert into Zipcodes (Code, City) values ('4600', 'Køge');
insert into Zipcodes (Code, City) values ('4621', 'Gadstrup');
insert into Zipcodes (Code, City) values ('4622', 'Havdrup');
insert into Zipcodes (Code, City) values ('4623', 'Lille-Skensved');
insert into Zipcodes (Code, City) values ('4632', 'Bjæverskov');
insert into Zipcodes (Code, City) values ('4640', 'Fakse');
insert into Zipcodes (Code, City) values ('4652', 'Hårlev');
insert into Zipcodes (Code, City) values ('4653', 'Karise');
insert into Zipcodes (Code, City) values ('4654', 'Fakse Ladeplads');
insert into Zipcodes (Code, City) values ('4660', 'Store-Heddinge');
insert into Zipcodes (Code, City) values ('4671', 'Strøby');
insert into Zipcodes (Code, City) values ('4672', 'Klippinge');
insert into Zipcodes (Code, City) values ('4673', 'Rødvig Stevns');
insert into Zipcodes (Code, City) values ('4681', 'Herfølge');
insert into Zipcodes (Code, City) values ('4682', 'Tureby');
insert into Zipcodes (Code, City) values ('4683', 'Rønnede');
insert into Zipcodes (Code, City) values ('4684', 'Holme-Olstrup');
insert into Zipcodes (Code, City) values ('4690', 'Haslev');
insert into Zipcodes (Code, City) values ('4700', 'Næstved');
insert into Zipcodes (Code, City) values ('4720', 'Præstø');
insert into Zipcodes (Code, City) values ('4733', 'Tappernøje');
insert into Zipcodes (Code, City) values ('4735', 'Mern');
insert into Zipcodes (Code, City) values ('4736', 'Karrebæksminde');
insert into Zipcodes (Code, City) values ('4750', 'Lundby');
insert into Zipcodes (Code, City) values ('4760', 'Vordingborg');
insert into Zipcodes (Code, City) values ('4771', 'Kalvehave');
insert into Zipcodes (Code, City) values ('4772', 'Langebæk');
insert into Zipcodes (Code, City) values ('4773', 'Stensved');
insert into Zipcodes (Code, City) values ('4780', 'Stege');
insert into Zipcodes (Code, City) values ('4791', 'Borre');
insert into Zipcodes (Code, City) values ('4792', 'Askeby');
insert into Zipcodes (Code, City) values ('4793', 'Bogø By');
insert into Zipcodes (Code, City) values ('4800', 'Nykøbing F.');
insert into Zipcodes (Code, City) values ('4817', 'His');
insert into Zipcodes (Code, City) values ('4840', 'Nørre-Alslev');
insert into Zipcodes (Code, City) values ('4850', 'Stubbekøbing');
insert into Zipcodes (Code, City) values ('4862', 'Guldborg');
insert into Zipcodes (Code, City) values ('4863', 'Eskilstrup');
insert into Zipcodes (Code, City) values ('4870', 'Rykene');
insert into Zipcodes (Code, City) values ('4871', 'Horbelev');
insert into Zipcodes (Code, City) values ('4872', 'Idestrup');
insert into Zipcodes (Code, City) values ('4873', 'Væggerløse');
insert into Zipcodes (Code, City) values ('4874', 'Gedser');
insert into Zipcodes (Code, City) values ('4880', 'Nysted');
insert into Zipcodes (Code, City) values ('4891', 'Toreby L.');
insert into Zipcodes (Code, City) values ('4892', 'Kettinge');
insert into Zipcodes (Code, City) values ('4894', 'Øster-Ulslev');
insert into Zipcodes (Code, City) values ('4895', 'Errindlev');
insert into Zipcodes (Code, City) values ('4900', 'Nakskov');
insert into Zipcodes (Code, City) values ('4912', 'Harpelunde');
insert into Zipcodes (Code, City) values ('4913', 'Horslunde');
insert into Zipcodes (Code, City) values ('4920', 'Søllested');
insert into Zipcodes (Code, City) values ('4930', 'Maribo');
insert into Zipcodes (Code, City) values ('4941', 'Bandholm');
insert into Zipcodes (Code, City) values ('4943', 'Torrig L.');
insert into Zipcodes (Code, City) values ('4944', 'Fejø');
insert into Zipcodes (Code, City) values ('4951', 'Nørreballe');
insert into Zipcodes (Code, City) values ('4952', 'Stokkemarke');
insert into Zipcodes (Code, City) values ('4953', 'Vesterborg');
insert into Zipcodes (Code, City) values ('4960', 'Holeby');
insert into Zipcodes (Code, City) values ('4970', 'Rødby');
insert into Zipcodes (Code, City) values ('4983', 'Dannemare');
insert into Zipcodes (Code, City) values ('4990', 'Sakskøbing');
insert into Zipcodes (Code, City) values ('5000', 'Odense C');
insert into Zipcodes (Code, City) values ('5100', 'Odense C (postboks)');
insert into Zipcodes (Code, City) values ('5200', 'Odense V');
insert into Zipcodes (Code, City) values ('5210', 'Odense NV');
insert into Zipcodes (Code, City) values ('5220', 'Odense SØ');
insert into Zipcodes (Code, City) values ('5230', 'Odense M');
insert into Zipcodes (Code, City) values ('5240', 'Odense NØ');
insert into Zipcodes (Code, City) values ('5250', 'Odense SV');
insert into Zipcodes (Code, City) values ('5260', 'Odense S');
insert into Zipcodes (Code, City) values ('5270', 'Odense N');
insert into Zipcodes (Code, City) values ('5290', 'Marslev');
insert into Zipcodes (Code, City) values ('5300', 'Kerteminde');
insert into Zipcodes (Code, City) values ('5320', 'Agedrup');
insert into Zipcodes (Code, City) values ('5330', 'Munkebo');
insert into Zipcodes (Code, City) values ('5350', 'Rynkeby');
insert into Zipcodes (Code, City) values ('5370', 'Mesinge');
insert into Zipcodes (Code, City) values ('5380', 'Dalby');
insert into Zipcodes (Code, City) values ('5390', 'Martofte');
insert into Zipcodes (Code, City) values ('5400', 'Bogense');
insert into Zipcodes (Code, City) values ('5450', 'Otterup');
insert into Zipcodes (Code, City) values ('5462', 'Morud');
insert into Zipcodes (Code, City) values ('5463', 'Harndrup');
insert into Zipcodes (Code, City) values ('5464', 'Brenderup Fyn');
insert into Zipcodes (Code, City) values ('5466', 'Asperup');
insert into Zipcodes (Code, City) values ('5471', 'Søndersø');
insert into Zipcodes (Code, City) values ('5474', 'Veflinge');
insert into Zipcodes (Code, City) values ('5485', 'Skamby');
insert into Zipcodes (Code, City) values ('5491', 'Blommenslyst');
insert into Zipcodes (Code, City) values ('5492', 'Vissenbjerg');
insert into Zipcodes (Code, City) values ('5500', 'Middelfart');
insert into Zipcodes (Code, City) values ('5540', 'Ullerslev');
insert into Zipcodes (Code, City) values ('5550', 'Langeskov');
insert into Zipcodes (Code, City) values ('5560', 'Aarup');
insert into Zipcodes (Code, City) values ('5580', 'Nørre Aaby');
insert into Zipcodes (Code, City) values ('5591', 'Gelsted');
insert into Zipcodes (Code, City) values ('5592', 'Ejby');
insert into Zipcodes (Code, City) values ('5600', 'Fåborg');
insert into Zipcodes (Code, City) values ('5610', 'Assens');
insert into Zipcodes (Code, City) values ('5620', 'Glamsbjerg');
insert into Zipcodes (Code, City) values ('5631', 'Ebberup');
insert into Zipcodes (Code, City) values ('5642', 'Millinge');
insert into Zipcodes (Code, City) values ('5672', 'Broby');
insert into Zipcodes (Code, City) values ('5683', 'Haarby');
insert into Zipcodes (Code, City) values ('5690', 'Tommerup');
insert into Zipcodes (Code, City) values ('5700', 'Svendborg');
insert into Zipcodes (Code, City) values ('5750', 'Ringe');
insert into Zipcodes (Code, City) values ('5762', 'Vester-Skerninge');
insert into Zipcodes (Code, City) values ('5771', 'Stenstrup');
insert into Zipcodes (Code, City) values ('5772', 'Kværndrup');
insert into Zipcodes (Code, City) values ('5792', 'Årslev');
insert into Zipcodes (Code, City) values ('5800', 'Nyborg');
insert into Zipcodes (Code, City) values ('5853', 'Ørbæk');
insert into Zipcodes (Code, City) values ('5854', 'Gislev');
insert into Zipcodes (Code, City) values ('5856', 'Ryslinge');
insert into Zipcodes (Code, City) values ('5863', 'Ferritslev Fyn');
insert into Zipcodes (Code, City) values ('5871', 'Frørup');
insert into Zipcodes (Code, City) values ('5874', 'Hesselager');
insert into Zipcodes (Code, City) values ('5881', 'Skårup Fyn');
insert into Zipcodes (Code, City) values ('5882', 'Vejstrup');
insert into Zipcodes (Code, City) values ('5883', 'Oure');
insert into Zipcodes (Code, City) values ('5884', 'Gudme');
insert into Zipcodes (Code, City) values ('5892', 'Gudbjerg Sydfyn');
insert into Zipcodes (Code, City) values ('5900', 'Rudkøbing');
insert into Zipcodes (Code, City) values ('5932', 'Humble');
insert into Zipcodes (Code, City) values ('5935', 'Bagenkop');
insert into Zipcodes (Code, City) values ('5953', 'Tranekær');
insert into Zipcodes (Code, City) values ('5960', 'Marstal');
insert into Zipcodes (Code, City) values ('5970', 'Ærøskøbing');
insert into Zipcodes (Code, City) values ('5985', 'Søby Ærø');
insert into Zipcodes (Code, City) values ('6000', 'Kolding');
insert into Zipcodes (Code, City) values ('6040', 'Egtved');
insert into Zipcodes (Code, City) values ('6051', 'Almind');
insert into Zipcodes (Code, City) values ('6052', 'Viuf');
insert into Zipcodes (Code, City) values ('6064', 'Jordrup');
insert into Zipcodes (Code, City) values ('6070', 'Christiansfeld');
insert into Zipcodes (Code, City) values ('6091', 'Bjert');
insert into Zipcodes (Code, City) values ('6092', 'Sønder Stenderup');
insert into Zipcodes (Code, City) values ('6093', 'Sjølund');
insert into Zipcodes (Code, City) values ('6094', 'Hejls');
insert into Zipcodes (Code, City) values ('6100', 'Haderslev');
insert into Zipcodes (Code, City) values ('6200', 'Aabenraa');
insert into Zipcodes (Code, City) values ('6230', 'Rødekro');
insert into Zipcodes (Code, City) values ('6240', 'Løgumkloster');
insert into Zipcodes (Code, City) values ('6261', 'Bredebro');
insert into Zipcodes (Code, City) values ('6270', 'Tønder');
insert into Zipcodes (Code, City) values ('6280', 'Højer');
insert into Zipcodes (Code, City) values ('6300', 'Gråsten');
insert into Zipcodes (Code, City) values ('6310', 'Broager');
insert into Zipcodes (Code, City) values ('6320', 'Egernsund');
insert into Zipcodes (Code, City) values ('6330', 'Padborg');
insert into Zipcodes (Code, City) values ('6340', 'Kruså');
insert into Zipcodes (Code, City) values ('6360', 'Tinglev');
insert into Zipcodes (Code, City) values ('6372', 'Bylderup-Bov');
insert into Zipcodes (Code, City) values ('6392', 'Bolderslev');
insert into Zipcodes (Code, City) values ('6400', 'Sønderborg');
insert into Zipcodes (Code, City) values ('6430', 'Nordborg');
insert into Zipcodes (Code, City) values ('6440', 'Augustenborg');
insert into Zipcodes (Code, City) values ('6470', 'Sydals');
insert into Zipcodes (Code, City) values ('6500', 'Vojens');
insert into Zipcodes (Code, City) values ('6510', 'Gram');
insert into Zipcodes (Code, City) values ('6520', 'Toftlund');
insert into Zipcodes (Code, City) values ('6534', 'Agerskov');
insert into Zipcodes (Code, City) values ('6535', 'Branderup J');
insert into Zipcodes (Code, City) values ('6541', 'Bevtoft');
insert into Zipcodes (Code, City) values ('6560', 'Sommersted');
insert into Zipcodes (Code, City) values ('6580', 'Vamdrup');
insert into Zipcodes (Code, City) values ('6600', 'Vejen');
insert into Zipcodes (Code, City) values ('6621', 'Gesten');
insert into Zipcodes (Code, City) values ('6622', 'Bække');
insert into Zipcodes (Code, City) values ('6623', 'Vorbasse');
insert into Zipcodes (Code, City) values ('6630', 'Rødding');
insert into Zipcodes (Code, City) values ('6640', 'Lunderskov');
insert into Zipcodes (Code, City) values ('6650', 'Brørup');
insert into Zipcodes (Code, City) values ('6660', 'Lintrup');
insert into Zipcodes (Code, City) values ('6670', 'Holsted');
insert into Zipcodes (Code, City) values ('6682', 'Hovborg');
insert into Zipcodes (Code, City) values ('6683', 'Føvling');
insert into Zipcodes (Code, City) values ('6690', 'Gørding');
insert into Zipcodes (Code, City) values ('6700', 'Esbjerg');
insert into Zipcodes (Code, City) values ('6701', 'Esbjerg (postboks)');
insert into Zipcodes (Code, City) values ('6705', 'Esbjerg Ø');
insert into Zipcodes (Code, City) values ('6710', 'Esbjerg V');
insert into Zipcodes (Code, City) values ('6715', 'Esbjerg N');
insert into Zipcodes (Code, City) values ('6720', 'Fanø');
insert into Zipcodes (Code, City) values ('6731', 'Tjæreborg');
insert into Zipcodes (Code, City) values ('6740', 'Bramming');
insert into Zipcodes (Code, City) values ('6752', 'Glejbjerg');
insert into Zipcodes (Code, City) values ('6753', 'Agerbæk');
insert into Zipcodes (Code, City) values ('6760', 'Ribe');
insert into Zipcodes (Code, City) values ('6771', 'Gredstedbro');
insert into Zipcodes (Code, City) values ('6780', 'Skærbæk');
insert into Zipcodes (Code, City) values ('6792', 'Rømø');
insert into Zipcodes (Code, City) values ('6800', 'Varde');
insert into Zipcodes (Code, City) values ('6818', 'Årre');
insert into Zipcodes (Code, City) values ('6823', 'Ansager');
insert into Zipcodes (Code, City) values ('6830', 'Nørre-Nebel');
insert into Zipcodes (Code, City) values ('6840', 'Oksbøl');
insert into Zipcodes (Code, City) values ('6851', 'Janderup Vestj.');
insert into Zipcodes (Code, City) values ('6852', 'Billum');
insert into Zipcodes (Code, City) values ('6853', 'Vejers Strand');
insert into Zipcodes (Code, City) values ('6854', 'Henne');
insert into Zipcodes (Code, City) values ('6855', 'Ovtrup');
insert into Zipcodes (Code, City) values ('6857', 'Blåvand');
insert into Zipcodes (Code, City) values ('6862', 'Tistrup');
insert into Zipcodes (Code, City) values ('6870', 'Ølgod');
insert into Zipcodes (Code, City) values ('6880', 'Tarm');
insert into Zipcodes (Code, City) values ('6893', 'Hemmet');
insert into Zipcodes (Code, City) values ('6900', 'Skjern');
insert into Zipcodes (Code, City) values ('6920', 'Videbæk');
insert into Zipcodes (Code, City) values ('6933', 'Kibæk');
insert into Zipcodes (Code, City) values ('6940', 'Lem St.');
insert into Zipcodes (Code, City) values ('6950', 'Ringkøbing');
insert into Zipcodes (Code, City) values ('6960', 'Hvide Sande');
insert into Zipcodes (Code, City) values ('6971', 'Spjald');
insert into Zipcodes (Code, City) values ('6973', 'Ørnhøj');
insert into Zipcodes (Code, City) values ('6980', 'Tim');
insert into Zipcodes (Code, City) values ('6990', 'Ulfborg');
insert into Zipcodes (Code, City) values ('7000', 'Fredericia');
insert into Zipcodes (Code, City) values ('7080', 'Børkop');
insert into Zipcodes (Code, City) values ('7100', 'Vejle');
insert into Zipcodes (Code, City) values ('7120', 'Vejle Øst');
insert into Zipcodes (Code, City) values ('7130', 'Juelsminde');
insert into Zipcodes (Code, City) values ('7140', 'Stouby');
insert into Zipcodes (Code, City) values ('7150', 'Barrit');
insert into Zipcodes (Code, City) values ('7160', 'Tørring');
insert into Zipcodes (Code, City) values ('7171', 'Uldum');
insert into Zipcodes (Code, City) values ('7173', 'Vonge');
insert into Zipcodes (Code, City) values ('7182', 'Bredsten');
insert into Zipcodes (Code, City) values ('7183', 'Randbøl');
insert into Zipcodes (Code, City) values ('7184', 'Vandel');
insert into Zipcodes (Code, City) values ('7190', 'Billund');
insert into Zipcodes (Code, City) values ('7200', 'Grindsted');
insert into Zipcodes (Code, City) values ('7250', 'Hejnsvig');
insert into Zipcodes (Code, City) values ('7260', 'Sønder-Omme');
insert into Zipcodes (Code, City) values ('7270', 'Stakroge');
insert into Zipcodes (Code, City) values ('7280', 'Sønder-Felding');
insert into Zipcodes (Code, City) values ('7300', 'Jelling');
insert into Zipcodes (Code, City) values ('7321', 'Gadbjerg');
insert into Zipcodes (Code, City) values ('7323', 'Give');
insert into Zipcodes (Code, City) values ('7330', 'Brande');
insert into Zipcodes (Code, City) values ('7361', 'Ejstrupholm');
insert into Zipcodes (Code, City) values ('7362', 'Hampen');
insert into Zipcodes (Code, City) values ('7400', 'Herning');
insert into Zipcodes (Code, City) values ('7430', 'Ikast');
insert into Zipcodes (Code, City) values ('7441', 'Bording');
insert into Zipcodes (Code, City) values ('7442', 'Engesvang');
insert into Zipcodes (Code, City) values ('7451', 'Sunds');
insert into Zipcodes (Code, City) values ('7470', 'Karup J.');
insert into Zipcodes (Code, City) values ('7480', 'Vildbjerg');
insert into Zipcodes (Code, City) values ('7490', 'Avlum');
insert into Zipcodes (Code, City) values ('7500', 'Holstebro');
insert into Zipcodes (Code, City) values ('7540', 'Haderup');
insert into Zipcodes (Code, City) values ('7550', 'Sørvad');
insert into Zipcodes (Code, City) values ('7560', 'Hjerm');
insert into Zipcodes (Code, City) values ('7570', 'Vemb');
insert into Zipcodes (Code, City) values ('7600', 'Struer');
insert into Zipcodes (Code, City) values ('7620', 'Lemvig');
insert into Zipcodes (Code, City) values ('7650', 'Bøvlingbjerg');
insert into Zipcodes (Code, City) values ('7660', 'Bækmarksbro');
insert into Zipcodes (Code, City) values ('7673', 'Harboøre');
insert into Zipcodes (Code, City) values ('7680', 'Thyborøn');
insert into Zipcodes (Code, City) values ('7700', 'Thisted');
insert into Zipcodes (Code, City) values ('7730', 'Hanstholm');
insert into Zipcodes (Code, City) values ('7741', 'Frøstrup');
insert into Zipcodes (Code, City) values ('7742', 'Vesløs');
insert into Zipcodes (Code, City) values ('7752', 'Snedsted');
insert into Zipcodes (Code, City) values ('7755', 'Bedsted Thy');
insert into Zipcodes (Code, City) values ('7760', 'Hurup Thy');
insert into Zipcodes (Code, City) values ('7770', 'Vestervig');
insert into Zipcodes (Code, City) values ('7790', 'Thyholm');
insert into Zipcodes (Code, City) values ('7800', 'Skive');
insert into Zipcodes (Code, City) values ('7830', 'Vinderup');
insert into Zipcodes (Code, City) values ('7840', 'Højslev');
insert into Zipcodes (Code, City) values ('7850', 'Stoholm Jyll.');
insert into Zipcodes (Code, City) values ('7860', 'Spøttrup');
insert into Zipcodes (Code, City) values ('7870', 'Roslev');
insert into Zipcodes (Code, City) values ('7884', 'Fur');
insert into Zipcodes (Code, City) values ('7900', 'Nykøbing M');
insert into Zipcodes (Code, City) values ('7950', 'Erslev');
insert into Zipcodes (Code, City) values ('7960', 'Karby');
insert into Zipcodes (Code, City) values ('7970', 'Redsted M.');
insert into Zipcodes (Code, City) values ('7980', 'Vils');
insert into Zipcodes (Code, City) values ('7990', 'Øster-Assels');
insert into Zipcodes (Code, City) values ('8000', 'Århus C');
insert into Zipcodes (Code, City) values ('8100', 'Århus C');
insert into Zipcodes (Code, City) values ('8200', 'Århus N');
insert into Zipcodes (Code, City) values ('8210', 'Århus V');
insert into Zipcodes (Code, City) values ('8220', 'Brabrand');
insert into Zipcodes (Code, City) values ('8230', 'Åbyhøj');
insert into Zipcodes (Code, City) values ('8240', 'Risskov');
insert into Zipcodes (Code, City) values ('8245', 'Risskov Ø');
insert into Zipcodes (Code, City) values ('8250', 'Egå');
insert into Zipcodes (Code, City) values ('8260', 'Viby J.');
insert into Zipcodes (Code, City) values ('8270', 'Højbjerg');
insert into Zipcodes (Code, City) values ('8300', 'Odder');
insert into Zipcodes (Code, City) values ('8305', 'Samsø');
insert into Zipcodes (Code, City) values ('8310', 'Tranbjerg J.');
insert into Zipcodes (Code, City) values ('8320', 'Mårslet');
insert into Zipcodes (Code, City) values ('8330', 'Beder');
insert into Zipcodes (Code, City) values ('8340', 'Malling');
insert into Zipcodes (Code, City) values ('8350', 'Hundslund');
insert into Zipcodes (Code, City) values ('8355', 'Solbjerg');
insert into Zipcodes (Code, City) values ('8361', 'Hasselager');
insert into Zipcodes (Code, City) values ('8362', 'Hørning');
insert into Zipcodes (Code, City) values ('8370', 'Hadsten');
insert into Zipcodes (Code, City) values ('8380', 'Trige');
insert into Zipcodes (Code, City) values ('8381', 'Mundelstrup');
insert into Zipcodes (Code, City) values ('8382', 'Hinnerup');
insert into Zipcodes (Code, City) values ('8400', 'Ebeltoft');
insert into Zipcodes (Code, City) values ('8410', 'Rønde');
insert into Zipcodes (Code, City) values ('8420', 'Knebel');
insert into Zipcodes (Code, City) values ('8444', 'Balle');
insert into Zipcodes (Code, City) values ('8450', 'Hammel');
insert into Zipcodes (Code, City) values ('8462', 'Harlev J');
insert into Zipcodes (Code, City) values ('8464', 'Galten');
insert into Zipcodes (Code, City) values ('8471', 'Sabro');
insert into Zipcodes (Code, City) values ('8472', 'Sporup');
insert into Zipcodes (Code, City) values ('8500', 'Grenå');
insert into Zipcodes (Code, City) values ('8520', 'Lystrup');
insert into Zipcodes (Code, City) values ('8530', 'Hjortshøj');
insert into Zipcodes (Code, City) values ('8541', 'Skødstrup');
insert into Zipcodes (Code, City) values ('8543', 'Hornslet');
insert into Zipcodes (Code, City) values ('8544', 'Mørke');
insert into Zipcodes (Code, City) values ('8550', 'Ryomgård');
insert into Zipcodes (Code, City) values ('8560', 'Kolind');
insert into Zipcodes (Code, City) values ('8570', 'Trustrup');
insert into Zipcodes (Code, City) values ('8581', 'Nimtofte');
insert into Zipcodes (Code, City) values ('8585', 'Glesborg');
insert into Zipcodes (Code, City) values ('8586', 'Ørum Djurs');
insert into Zipcodes (Code, City) values ('8592', 'Anholt');
insert into Zipcodes (Code, City) values ('8600', 'Silkeborg');
insert into Zipcodes (Code, City) values ('8620', 'Kjellerup');
insert into Zipcodes (Code, City) values ('8632', 'Lemming');
insert into Zipcodes (Code, City) values ('8641', 'Sorring');
insert into Zipcodes (Code, City) values ('8643', 'Ans By');
insert into Zipcodes (Code, City) values ('8653', 'Them');
insert into Zipcodes (Code, City) values ('8654', 'Bryrup');
insert into Zipcodes (Code, City) values ('8660', 'Skanderborg');
insert into Zipcodes (Code, City) values ('8670', 'Låsby');
insert into Zipcodes (Code, City) values ('8680', 'Ry');
insert into Zipcodes (Code, City) values ('8700', 'Horsens');
insert into Zipcodes (Code, City) values ('8721', 'Daugård');
insert into Zipcodes (Code, City) values ('8722', 'Hedensted');
insert into Zipcodes (Code, City) values ('8723', 'Løsning');
insert into Zipcodes (Code, City) values ('8732', 'Hovedgård');
insert into Zipcodes (Code, City) values ('8740', 'Brædstrup');
insert into Zipcodes (Code, City) values ('8751', 'Gedved');
insert into Zipcodes (Code, City) values ('8752', 'Østbirk');
insert into Zipcodes (Code, City) values ('8762', 'Flemming');
insert into Zipcodes (Code, City) values ('8763', 'Rask Mølle');
insert into Zipcodes (Code, City) values ('8765', 'Klovborg');
insert into Zipcodes (Code, City) values ('8766', 'Nørre-Snede');
insert into Zipcodes (Code, City) values ('8781', 'Stenderup');
insert into Zipcodes (Code, City) values ('8783', 'Hornsyld');
insert into Zipcodes (Code, City) values ('8800', 'Viborg');
insert into Zipcodes (Code, City) values ('8830', 'Tjele');
insert into Zipcodes (Code, City) values ('8831', 'Løgstrup');
insert into Zipcodes (Code, City) values ('8832', 'Skals');
insert into Zipcodes (Code, City) values ('8840', 'Rødkærsbro');
insert into Zipcodes (Code, City) values ('8850', 'Bjerringbro');
insert into Zipcodes (Code, City) values ('8860', 'Ulstrup');
insert into Zipcodes (Code, City) values ('8870', 'Langå');
insert into Zipcodes (Code, City) values ('8881', 'Thorsø');
insert into Zipcodes (Code, City) values ('8882', 'Fårvang');
insert into Zipcodes (Code, City) values ('8883', 'Gjern');
insert into Zipcodes (Code, City) values ('8900', 'Randers');
insert into Zipcodes (Code, City) values ('8950', 'Ørsted');
insert into Zipcodes (Code, City) values ('8961', 'Allingåbro');
insert into Zipcodes (Code, City) values ('8963', 'Auning');
insert into Zipcodes (Code, City) values ('8970', 'Havndal');
insert into Zipcodes (Code, City) values ('8981', 'Spentrup');
insert into Zipcodes (Code, City) values ('8983', 'Gjerlev J');
insert into Zipcodes (Code, City) values ('8990', 'Fårup');
insert into Zipcodes (Code, City) values ('9000', 'Aalborg');
insert into Zipcodes (Code, City) values ('9100', 'Aalborg (Postboks)');
insert into Zipcodes (Code, City) values ('9200', 'Aalborg SV');
insert into Zipcodes (Code, City) values ('9210', 'Aalborg SØ');
insert into Zipcodes (Code, City) values ('9220', 'Aalborg Øst');
insert into Zipcodes (Code, City) values ('9230', 'Svenstrup J.');
insert into Zipcodes (Code, City) values ('9240', 'Nibe');
insert into Zipcodes (Code, City) values ('9260', 'Gistrup');
insert into Zipcodes (Code, City) values ('9270', 'Klarup');
insert into Zipcodes (Code, City) values ('9280', 'Storvorde');
insert into Zipcodes (Code, City) values ('9293', 'Kongerslev');
insert into Zipcodes (Code, City) values ('9300', 'Sæby');
insert into Zipcodes (Code, City) values ('9310', 'Vodskov');
insert into Zipcodes (Code, City) values ('9320', 'Hjallerup');
insert into Zipcodes (Code, City) values ('9330', 'Dronninglund');
insert into Zipcodes (Code, City) values ('9340', 'Asaa');
insert into Zipcodes (Code, City) values ('9352', 'Dybvad');
insert into Zipcodes (Code, City) values ('9362', 'Gandrup');
insert into Zipcodes (Code, City) values ('9370', 'Hals');
insert into Zipcodes (Code, City) values ('9380', 'Vestbjerg');
insert into Zipcodes (Code, City) values ('9381', 'Sulsted');
insert into Zipcodes (Code, City) values ('9382', 'Tylstrup');
insert into Zipcodes (Code, City) values ('9400', 'Nørresundby');
insert into Zipcodes (Code, City) values ('9430', 'Vadum');
insert into Zipcodes (Code, City) values ('9440', 'Aabybro');
insert into Zipcodes (Code, City) values ('9460', 'Brovst');
insert into Zipcodes (Code, City) values ('9480', 'Løkken');
insert into Zipcodes (Code, City) values ('9490', 'Pandrup');
insert into Zipcodes (Code, City) values ('9492', 'Blokhus');
insert into Zipcodes (Code, City) values ('9493', 'Saltum');
insert into Zipcodes (Code, City) values ('9500', 'Hobro');
insert into Zipcodes (Code, City) values ('9510', 'Arden');
insert into Zipcodes (Code, City) values ('9520', 'Skørping');
insert into Zipcodes (Code, City) values ('9530', 'Støvring');
insert into Zipcodes (Code, City) values ('9541', 'Suldrup');
insert into Zipcodes (Code, City) values ('9550', 'Mariager');
insert into Zipcodes (Code, City) values ('9560', 'Hadsund');
insert into Zipcodes (Code, City) values ('9574', 'Bælum');
insert into Zipcodes (Code, City) values ('9575', 'Terndrup');
insert into Zipcodes (Code, City) values ('9600', 'Aars');
insert into Zipcodes (Code, City) values ('9610', 'Nørager');
insert into Zipcodes (Code, City) values ('9620', 'Aalestrup');
insert into Zipcodes (Code, City) values ('9631', 'Gedsted');
insert into Zipcodes (Code, City) values ('9632', 'Møldrup');
insert into Zipcodes (Code, City) values ('9640', 'Farsø');
insert into Zipcodes (Code, City) values ('9670', 'Løgstør');
insert into Zipcodes (Code, City) values ('9681', 'Ranum');
insert into Zipcodes (Code, City) values ('9690', 'Fjerritslev');
insert into Zipcodes (Code, City) values ('9700', 'Brønderslev');
insert into Zipcodes (Code, City) values ('9740', 'Jerslev J.');
insert into Zipcodes (Code, City) values ('9750', 'Øster-Vrå');
insert into Zipcodes (Code, City) values ('9760', 'Vrå');
insert into Zipcodes (Code, City) values ('9800', 'Hjørring');
insert into Zipcodes (Code, City) values ('9830', 'Tårs');
insert into Zipcodes (Code, City) values ('9850', 'Hirtshals');
insert into Zipcodes (Code, City) values ('9870', 'Sindal');
insert into Zipcodes (Code, City) values ('9881', 'Bindslev');
insert into Zipcodes (Code, City) values ('9900', 'Frederikshavn');
insert into Zipcodes (Code, City) values ('9940', 'Læsø');
insert into Zipcodes (Code, City) values ('9960', 'Østerby Havn');
insert into Zipcodes (Code, City) values ('9970', 'Strandby');
insert into Zipcodes (Code, City) values ('9981', 'Jerup');
insert into Zipcodes (Code, City) values ('9982', 'Ålbæk');
insert into Zipcodes (Code, City) values ('9990', 'Skagen');



/* AccessRight */
insert into Access(AccessName) values ('Admin');
insert into Access(AccessName) values ('User');

/* Users */
Insert into Users(Email, Password, Access, PersonName, HomePhone, WorkPhone, Address, Zipcode) Values('admin@dania.dk', 'secret', 1, 'Admin', '0000000000', '0000000000', 'Bredgadevej 10', '8800');
Insert into Users(Email, Password, Access, PersonName, HomePhone, WorkPhone, Address, Zipcode) Values('user@dania.dk', 'secret', 2, 'User', '0000000000', '0000000000', 'Bredgadevej 10', '8800');
Insert into Users(Email, Password, Access, PersonName, HomePhone, WorkPhone, Address, Zipcode) Values('user2@dania.dk', 'secret', 2, 'User2', '0000000000', '0000000000', 'Bredgadevej 10', '8800');
/* Goods */
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Banana', 5.0, 10, 2);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Pølser', 30.0, 15, 3);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Pizza', 40.0, 20, 5);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Pasta', 10.0, 20, 5);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Tomater', 2.5, 19, 4);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Æble', 2.0, 100, 6);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Appelsin', 3.0, 50, 4);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Pære', 5.0, 20, 2);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Agurk', 8.0, 20, 2);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Løg', 20.0, 40, 2);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Svinekød', 45.0, 15, 1);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Kylling Brest', 30.0, 50, 5);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Kylling', 60.0, 10, 2);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Fiskpind', 20.0, 15, 3);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Ton', 5.0, 10, 2);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Kyllinglår', 45.0, 50, 6);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Gulerod', 5.0, 100, 5);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('kartofler', 50.0, 40, 5);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Majs', 10.0, 15, 2);
Insert into Goods(ProductName, Price, Amount, AmountLimit) values ('Sild', 20.0, 50, 5);